name: Verification Tests

on: push

jobs:
  ci:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17.6'
    - name: Setup Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.5'
    - name: Install Prerequisites
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Run Tests
      run: make test
    - name: Check Version
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        version=$(beschi --version | awk '{print $NF}')
        git_tag=$(git describe --tags)
        if [[ $version != $git_tag ]]; then
          echo "Git tag does not match version string."
          exit 1
        fi
    - name: Build Distribution Package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        rm -rf dist
        python -m build
    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
