name: Verification Tests

on: push

jobs:
  ci:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17.6'
    - name: Install Prerequisites
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Run Tests
      run: make test
